import { App, ButtonComponent, DropdownComponent, Modal, Notice, Plugin, PluginSettingTab, Setting, TFile, TextComponent } from "obsidian";
import { applyOperation, Frontmatter, Operation, parseFrontmatter, planOperation, ChangePlan } from "./core";

interface TundraSettings { lastOperation?: Operation; lastBatch?: Batch; }
interface Batch { id: string; createdAt: string; operation: Operation; files: Array<{ path: string; original: string; after?: string }>; summary: { changed: number; skipped: number; failed: number; unchanged: number }; }
const DEFAULT_SETTINGS: TundraSettings = {};

export default class TundraPlugin extends Plugin {
  settings: TundraSettings = DEFAULT_SETTINGS;
  async onload() { this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData()); this.addCommand({ id: "open-wrangler", name: "Open frontmatter wrangler", callback: () => new WranglerModal(this.app, this).open() }); this.addRibbonIcon("wrench", "Open frontmatter wrangler", () => new WranglerModal(this.app, this).open()); this.addSettingTab(new TundraSettingTab(this.app, this)); }
  async saveSettings() { await this.saveData(this.settings); }
}

class TundraSettingTab extends PluginSettingTab { constructor(app: App, private plugin: TundraPlugin) { super(app, plugin); } display() { const { containerEl } = this; containerEl.empty(); containerEl.createEl("h2", { text: "Tundra Frontmatter Wrangler" }); containerEl.createEl("p", { text: "Offline-first metadata operations. Every write is journaled for rollback." }); new Setting(containerEl).setName("Open wrangler").setDesc("Review and apply a bulk operation").addButton(b => b.setButtonText("Open").setCta().onClick(() => new WranglerModal(this.app, this.plugin).open())); if (this.plugin.settings.lastBatch) new Setting(containerEl).setName("Most recent batch").setDesc(`${this.plugin.settings.lastBatch.summary.changed} changed · ${this.plugin.settings.lastBatch.createdAt}`).addButton(b => b.setButtonText("Rollback").onClick(() => rollback(this.app, this.plugin))); } }

class WranglerModal extends Modal {
  private step = 0; private files: TFile[] = []; private included = new Set<string>(); private plans: ChangePlan[] = []; private reviewed = new Set<string>(); private operation: Operation = { kind: "rename", oldKey: "", newKey: "", collision: "skip" }; private cancelled = false; private query = ""; private folder = ""; private recursive = true; private filterKey = ""; private filterValue = ""; private selectionStats = { withFrontmatter: 0, withoutFrontmatter: 0, skipped: 0 };
  private steps = ["Select", "Inspect", "Configure", "Preview", "Apply", "Review"];
  constructor(app: App, private plugin: TundraPlugin) { super(app); this.modalEl.addClass("tundra-modal"); }
  onOpen() { this.render(); }
  onClose() { this.contentEl.empty(); }
  private render() { const c = this.contentEl; c.empty(); c.createEl("div", { cls: "tundra-header", text: "Tundra Frontmatter Wrangler" }); const nav = c.createDiv("tundra-steps"); this.steps.forEach((s, i) => { const b = nav.createEl("button", { text: `${i + 1}. ${s}`, cls: i === this.step ? "is-active" : "" }); b.setAttribute("aria-current", i === this.step ? "step" : "false"); b.onclick = () => { if (i <= this.step || (i === 1 && this.files.length)) { this.step = i; this.render(); } }; }); const body = c.createDiv("tundra-body"); if (this.step === 0) this.renderSelect(body); if (this.step === 1) this.renderInspect(body); if (this.step === 2) this.renderConfigure(body); if (this.step === 3) this.renderPreview(body); if (this.step === 4) this.renderApply(body); if (this.step === 5) this.renderReview(body); }
  private footer(parent: HTMLElement, next: string, action: () => void, back = true) { const f = parent.createDiv("tundra-footer"); if (back) new ButtonComponent(f).setButtonText("Back").onClick(() => { this.step--; this.render(); }); new ButtonComponent(f).setButtonText(next).setCta().onClick(action); }
  private renderSelect(parent: HTMLElement) { parent.createEl("p", { text: "Choose a safe working set. Selection stays local to this vault." }); new Setting(parent).setName("Folder").setDesc("Leave blank for the whole vault").addText(t => t.setPlaceholder("Projects/2026").setValue(this.folder).onChange(v => { this.folder = v.trim(); })); new Setting(parent).setName("Include subfolders").addToggle(t => t.setValue(this.recursive).onChange(v => this.recursive = v)); new Setting(parent).setName("Path or text query").setDesc("Matches the note path or its body").addText(t => t.setPlaceholder("meeting").setValue(this.query).onChange(v => this.query = v)); new Setting(parent).setName("Property filter").setDesc("Exact top-level property value").addText(t => t.setPlaceholder("status").setValue(this.filterKey).onChange(v => this.filterKey = v)).addText(t => t.setPlaceholder("active").setValue(this.filterValue).onChange(v => this.filterValue = v)); const run = parent.createDiv("tundra-actions"); new ButtonComponent(run).setButtonText("Build inventory").setCta().onClick(async () => { await this.selectFiles(); this.step = 1; this.render(); }); }
  private async selectFiles() { const all = this.app.vault.getMarkdownFiles(); this.files = []; this.selectionStats = { withFrontmatter: 0, withoutFrontmatter: 0, skipped: 0 }; for (const file of all) { if (this.folder) { const prefix = this.folder.replace(/\\/g, "/").replace(/\/$/, "") + "/"; const path = file.path.replace(/\\/g, "/"); if (!(path === this.folder || (this.recursive ? path.startsWith(prefix) : path.slice(0, -file.name.length - 1) === this.folder))) continue; } const content = await this.app.vault.read(file); const parsed = parseFrontmatter(content); if (this.query && !file.path.toLowerCase().includes(this.query.toLowerCase()) && !content.toLowerCase().includes(this.query.toLowerCase())) continue; if (this.filterKey && String(parsed.frontmatter[this.filterKey] ?? "") !== this.filterValue) continue; this.files.push(file); if (parsed.hasFrontmatter && parsed.safe) this.selectionStats.withFrontmatter++; else if (!parsed.hasFrontmatter) this.selectionStats.withoutFrontmatter++; else this.selectionStats.skipped++; } this.included = new Set(this.files.map(f => f.path)); }
  private renderInspect(parent: HTMLElement) { parent.createEl("h3", { text: "Review selection" }); parent.createEl("p", { text: `${this.included.size} selected · ${this.selectionStats.withFrontmatter} with frontmatter · ${this.selectionStats.withoutFrontmatter} without frontmatter · ${this.selectionStats.skipped} will be skipped` }); parent.createEl("p", { text: "Uncheck any note to exclude it. Unsafe or malformed frontmatter is reported during preview." }); const inventory = new Map<string, { count: number; types: Set<string>; sample?: string }>(); for (const file of this.files) { const cache = this.app.metadataCache.getFileCache(file); for (const [key, value] of Object.entries(cache?.frontmatter ?? {})) { const item = inventory.get(key) ?? { count: 0, types: new Set<string>() }; item.count++; item.types.add(Array.isArray(value) ? "list" : typeof value); if (item.sample === undefined && value !== undefined) item.sample = String(value).slice(0, 80); inventory.set(key, item); } } if (inventory.size) { parent.createEl("h4", { text: "Property inventory" }); const table = parent.createEl("table", { cls: "tundra-inventory" }); const head = table.createEl("tr"); ["Property", "Occurrences", "Types", "Representative value"].forEach(text => head.createEl("th", { text })); for (const [key, item] of inventory) { const row = table.createEl("tr"); row.createEl("td", { text: key }); row.createEl("td", { text: String(item.count) }); row.createEl("td", { text: [...item.types].join(", ") }); row.createEl("td", { text: item.sample ?? "" }); } } const list = parent.createDiv("tundra-checklist"); for (const file of this.files) { const row = list.createDiv("tundra-check-row"); const label = row.createEl("label"); const cb = label.createEl("input", { type: "checkbox" }); cb.checked = this.included.has(file.path); cb.onchange = () => cb.checked ? this.included.add(file.path) : this.included.delete(file.path); label.createSpan({ text: ` ${file.path}` }); } this.footer(parent, "Configure", () => { this.step = 2; this.render(); }); }
  private renderConfigure(parent: HTMLElement) { parent.createEl("h3", { text: "Configure operation" }); const setting = new Setting(parent).setName("Operation").setDesc("Only top-level properties are changed"); setting.addDropdown(d => d.addOptions({ rename: "Rename property", remove: "Remove property (destructive)", "add-tags": "Add tags", "remove-tags": "Remove tags", "replace-tag": "Replace tag", "normalize-tags": "Normalize tags by exact rule", reorder: "Reorder schema", format: "Format only" }).setValue(this.operation.kind).onChange(v => { this.operation = { kind: v as Operation["kind"], collision: "skip" }; this.render(); })); if (["rename", "remove"].includes(this.operation.kind)) { this.textSetting(parent, "Property key", "oldKey", this.operation.oldKey ?? ""); if (this.operation.kind === "rename") { this.textSetting(parent, "New key", "newKey", this.operation.newKey ?? ""); new Setting(parent).setName("Collision handling").addDropdown(d => d.addOptions({ keep: "Keep existing new key", replace: "Replace with old value", merge: "Merge values", skip: "Skip collided note" }).setValue(this.operation.collision ?? "skip").onChange(v => this.operation.collision = v as Operation["collision"])); } } else if (["add-tags", "remove-tags"].includes(this.operation.kind)) this.textSetting(parent, "Tags (comma separated)", "tags", (this.operation.tags ?? []).join(", ")); else if (this.operation.kind === "replace-tag") { this.textSetting(parent, "From tag", "fromTag", this.operation.fromTag ?? ""); this.textSetting(parent, "To tag", "toTag", this.operation.toTag ?? ""); this.textSetting(parent, "Optional namespace/prefix", "namespace", this.operation.namespace ?? ""); } else if (this.operation.kind === "normalize-tags") { this.textSetting(parent, "Exact rule description", "rules", this.operation.rules ?? "lowercase, spaces to hyphens, slash separators"); this.textSetting(parent, "Optional namespace/prefix", "namespace", this.operation.namespace ?? ""); } else if (this.operation.kind === "reorder") { this.textSetting(parent, "Preferred keys (comma separated)", "order", (this.operation.order ?? []).join(", ")); new Setting(parent).setName("Unknown keys").addDropdown(d => d.addOptions({ after: "Keep after preferred keys", before: "Keep before preferred keys" }).setValue(this.operation.unknownPosition ?? "after").onChange(v => this.operation.unknownPosition = v as "before" | "after")); } if (this.operation.kind === "remove") parent.createEl("p", { cls: "tundra-warning", text: "Removing a property changes note files. A recovery journal is created, but confirm the exact key and count." }); this.footer(parent, "Preview", () => { this.step = 3; this.buildPlan().then(() => this.render()); }); }
  private textSetting(parent: HTMLElement, name: string, key: keyof Operation, value: string) { new Setting(parent).setName(name).addText(t => t.setValue(value).onChange(v => { if (key === "tags" || key === "order") (this.operation[key] as string[] | undefined) = v.split(",").map(s => s.trim()).filter(Boolean); else (this.operation[key] as string | undefined) = v; })); }
  private async buildPlan() { const notes: Array<{ path: string; content: string }> = []; for (const file of this.files.filter(f => this.included.has(f.path))) notes.push({ path: file.path, content: await this.app.vault.read(file) }); this.plans = planOperation(notes, this.operation); this.reviewed.clear(); }
  private renderPreview(parent: HTMLElement) { const changed = this.plans.filter(p => p.status === "changed"); const skipped = this.plans.filter(p => p.status === "skipped"); parent.createEl("h3", { text: "Preview and confirmation" }); parent.createEl("p", { text: `${changed.length} will change · ${skipped.length} skipped · ${this.plans.filter(p => p.status === "unchanged").length} unchanged` }); const details = parent.createEl("details"); details.open = true; details.createEl("summary", { text: "Inspect and review every affected note" }); const affected = details.createDiv("tundra-diffs"); for (const plan of this.plans) if (plan.status === "changed" || plan.status === "skipped") { const d = affected.createEl("details"); d.createEl("summary", { text: `${plan.status === "changed" ? "Change" : "Skip"}: ${plan.path}${plan.reason ? ` — ${plan.reason}` : ""}` }); if (plan.status === "changed") { const review = d.createEl("label"); const cb = review.createEl("input", { type: "checkbox" }); cb.checked = this.reviewed.has(plan.path); cb.onchange = () => cb.checked ? this.reviewed.add(plan.path) : this.reviewed.delete(plan.path); review.createSpan({ text: " I reviewed this diff" }); d.createEl("pre", { text: `- before: ${plan.before.slice(0, 700)}\n+ after: ${(plan.after ?? "").slice(0, 700)}` }); } } parent.createEl("p", { cls: "tundra-note", text: "Apply writes one note at a time. Original content for each changed note is stored in the most recent recovery journal." }); const f = parent.createDiv("tundra-footer"); new ButtonComponent(f).setButtonText("Back").onClick(() => { this.step = 2; this.render(); }); const apply = new ButtonComponent(f).setButtonText("Confirm and apply").setCta(); apply.setDisabled(!changed.every(p => this.reviewed.has(p.path))); apply.onClick(() => { if (!changed.every(p => this.reviewed.has(p.path))) return; if (this.operation.kind === "remove" && !window.confirm(`Remove property ${this.operation.oldKey} from ${changed.length} notes? This changes note files.`)) return; this.step = 4; this.render(); }); }
  private renderApply(parent: HTMLElement) { parent.createEl("h3", { text: "Applying changes" }); const progress = parent.createEl("progress", { attr: { max: String(this.plans.length), value: "0" } }); const status = parent.createEl("p", { text: "Starting…", cls: "tundra-status" }); new ButtonComponent(parent).setButtonText("Cancel after current note").onClick(() => this.cancelled = true); void (async () => { const batch: Batch = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), operation: this.operation, files: [], summary: { changed: 0, skipped: 0, failed: 0, unchanged: 0 } }; for (let i = 0; i < this.plans.length; i++) { if (this.cancelled) { status.setText("Cancelled. Notes already completed remain journaled."); break; } const p = this.plans[i]; progress.value = i + 1; status.setText(`${i + 1}/${this.plans.length}: ${p.path}`); if (p.status !== "changed" || !p.after) { batch.summary[p.status]++; continue; } const file = this.app.vault.getAbstractFileByPath(p.path); if (!(file instanceof TFile)) { batch.summary.failed++; continue; } try { const current = await this.app.vault.read(file); if (current !== p.before) { batch.summary.skipped++; continue; } batch.files.push({ path: p.path, original: p.before, after: p.after }); await this.app.vault.modify(file, p.after); batch.summary.changed++; } catch { batch.summary.failed++; } } await this.plugin.saveData(Object.assign(this.plugin.settings, { lastBatch: batch })); this.step = 5; this.render(); })(); }
  private renderReview(parent: HTMLElement) { const batch = this.plugin.settings.lastBatch; parent.createEl("h3", { text: "Run complete" }); if (!batch) { parent.createEl("p", { text: "No batch was recorded." }); return; } parent.createEl("p", { text: `${batch.summary.changed} changed · ${batch.summary.skipped} skipped · ${batch.summary.failed} failed · ${batch.summary.unchanged} unchanged` }); new ButtonComponent(parent).setButtonText("Rollback most recent batch").onClick(async () => { await rollback(this.app, this.plugin); this.render(); }); new ButtonComponent(parent).setButtonText("Open operation log").onClick(() => new LogModal(this.app, batch).open()); this.footer(parent, "Done", () => this.close(), false); }
}

async function rollback(app: App, plugin: TundraPlugin) { const batch = plugin.settings.lastBatch; if (!batch) { new Notice("No recovery journal is available."); return; } if (!window.confirm(`Restore ${batch.files.length} note(s) from the most recent journal?`)) return; let restored = 0; let skipped = 0; for (const entry of batch.files) { const file = app.vault.getAbstractFileByPath(entry.path); if (!(file instanceof TFile)) { skipped++; continue; } try { const current = await app.vault.read(file); if (entry.after !== undefined && current !== entry.after) { skipped++; continue; } await app.vault.modify(file, entry.original); restored++; } catch { skipped++; } } new Notice(`Restored ${restored} of ${batch.files.length} notes${skipped ? `; ${skipped} skipped because they changed or disappeared` : ""}.`); }
class LogModal extends Modal { constructor(app: App, private batch: Batch) { super(app); } onOpen() { this.contentEl.createEl("h3", { text: "Tundra operation log" }); this.contentEl.createEl("pre", { text: JSON.stringify(this.batch, null, 2) }); } onClose() { this.contentEl.empty(); } }
